apiVersion: vdb.teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: rdbms-example
spec:
  name: rdbms-karaf
  runtime: karaf
  env:
  - name: DEBUG
    value: "true"
  build:
    gitSource:
      uri: https://github.com/teiid/teiid-openshift-examples
      reference: '7.3-1.0.x'
    incremental: true
    env:
    - name: MAVEN_CLEAR_REPO
      value: 'true'
    - name: MAVEN_ARGS_APPEND
      value: '-Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 -Popenshift -am -pl rdbms-example'
    - name: ARTIFACT_DIR
      value: 'rdbms-example/target/'
