apiVersion: vdb.teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: rdbms-new-vdb
spec:
  name: rdbms-vdb-changes
  env:
  - name: JAVA_APP_DIR
    value: /deployments
  - name: JAVA_OPTIONS
    value: -Djava.net.preferIPv4Stack=true -Duser.home=/tmp -Djava.net.preferIPv4Addresses=true
  - name: NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: JAVA_DEBUG
    value: "true"
  - name: KUBERNETES_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  build:
    gitSource:
      uri: https://github.com/teiid/teiid-openshift-examples
      reference: 7.3-1.0.x
    env:
    - name: MAVEN_PROJECT
      value: rdbms-example/
    - name: MAVEN_ARGS_APPEND
      value: -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 -Popenshift -am -pl $(MAVEN_PROJECT)
    - name: ARTIFACT_DIR
      value: $(MAVEN_PROJECT)target/
    sourceFileChanges:
    - relativePath: rdbms-example/src/main/resources/application.properties
      contents: |
        spring.datasource.sampledb.jdbc-url=jdbc:postgresql://postgresql/sampledb
        spring.datasource.sampledb.username=user
        spring.datasource.sampledb.password=mypassword
        spring.datasource.sampledb.driver-class-name=org.postgresql.Driver
        spring.datasource.sampledb.platform=sampledb
        teiid.jdbc-enable=true
        teiid.vdb-file=new-vdb.ddl
    - relativePath: rdbms-example/src/main/resources/new-vdb.ddl
      contents: |
        CREATE DATABASE customer OPTIONS (ANNOTATION 'Customer VDB');
        USE DATABASE customer;

        CREATE FOREIGN DATA WRAPPER postgresql;
        CREATE SERVER sampledb TYPE 'NONE' FOREIGN DATA WRAPPER postgresql OPTIONS ("jndi-name" 'sampledb');

        CREATE SCHEMA accounts SERVER sampledb;
        CREATE VIRTUAL SCHEMA portfolio;

        SET SCHEMA accounts;
        IMPORT FOREIGN SCHEMA public FROM SERVER sampledb INTO accounts OPTIONS("importer.useFullSchemaName" 'false');

        SET SCHEMA portfolio;

        CREATE VIEW CustomerZip(id bigint PRIMARY KEY, name string, ssn string, zip string) AS 
            SELECT c.ID as id, c.NAME as name, c.SSN as ssn, a.ZIP as zip 
            FROM accounts.CUSTOMER c LEFT OUTER JOIN accounts.ADDRESS a 
            ON c.ID = a.CUSTOMER_ID;