apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: teiid.0.0.1
  namespace: placeholder
  annotations:
    categories: "Database, Integration & Delivery"
    certified: "false"
    description: Teiid Cloud Operator for deployment and management of Virtual Database services.
    repository: https://github.com/teiid/teiid-operator
    containerImage: quay.io/teiid/teiid-operator:0.0.1
    createdAt: 2019-06-24T12:48:22Z
    support: Red Hat, Inc.
    tectonic-visibility: ocs
    alm-examples: |-
      [
        {"apiVersion":core.teiid.io/v1alpha1","kind":"VirtualDatabase","metadata":{"name":"rdbms-springboot"},"spec":{"env":[{"name":"JAVA_APP_DIR","value":"/deployments"},{"name":"JAVA_OPTIONS","value":"-Djava.net.preferIPv4Stack=true -Duser.home=/tmp -Djava.net.preferIPv4Addresses=true"},{"name":"NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"SPRING_DATASOURCE_SAMPLEDB_USERNAME","value":"user"},{"name":"SPRING_DATASOURCE_SAMPLEDB_PASSWORD","value":"mypassword"},{"name":"SPRING_DATASOURCE_SAMPLEDB_DATABASENAME","value":"sampledb"},{"name":"SPRING_DATASOURCE_SAMPLEDB_JDBCURL","value":"jdbc:postgresql://postgresql/$(SPRING_DATASOURCE_SAMPLEDB_DATABASENAME)"},{"name":"JAVA_DEBUG","value":"true"},{"name":"KUBERNETES_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"build":{"gitSource":{"uri":"https://github.com/teiid/teiid-openshift-examples","reference":"7.3-1.0.x"},"env":[{"name":"MAVEN_PROJECT","value":"rdbms-example/"},{"name":"MAVEN_ARGS_APPEND","value":"-Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 -Popenshift -am -pl $(MAVEN_PROJECT)"},{"name":"ARTIFACT_DIR","value":"$(MAVEN_PROJECT)target/"}]}}}
      ]
  labels:
    operator-teiid: "true"
spec:
  displayName: Teiid Cloud
  description: Teiid Cloud Operator for deployment and management of quarkus services.
  keywords:
  - teiid
  - cloud
  - vdb
  - operator
  - springboot
  version: 0.0.1
  maturity: alpha
  maintainers:
  - name: Red Hat, Inc.
    email: bsig-cloud@redhat.com
  provider:
    name: Red Hat, Inc.
  links:
  - name: Product Page
    url: http://teiid.io/
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAALUAAABQCAYAAABf2jSYAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4gMbEwMT5hO1UwAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAgAElEQVR42u2deXxU1dnHf+fce2ffkkz2PWQPe4jsyqKIKPqKS13Qtra+rVp8Lba41Frta61Sy6vS1+V1XxBxiRsIguxr2AIJJEAgZN8zyUxmMsu995z3jyyGpRUwtFjv9/MJMxkyd86c85vnPud3nnMH0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQOCOI1gUa58qu4oOkYFQeH+zjLvt0NdZsLMKe/eWEc04AiAAMAIwAVABuAJAkkT79+3nKtMkXqQOfT//dO37k1Js19Z0nBIGSmLwZZGA/c84Hc2x4748CwN8rZm+vsBUAMgD2bx2pn1j0Knlk/s/5SZ1GAAgATAAcAPS9HaECCPV2Du+9r/b+rbH3MQZA1ekkPmXiGHMwGIpmnBnBQXr/HwCQmhSH5MQ4cM6JQa8TFr/6PmluddUBqAcgM86Vkg3v8zMd6H3rl57cfuxbv5RfaP1dXHJIuuzGe9SE2CjW1+ZeUZtffPNj69LClQavz2/mnNsARPcKsgFAR+993771S9nZ9Mm/ffqxq/ggCkblnfBY4Yp1Vz757BvJiqJYAegASL2CzgSQDcA+QLBK7y3vFbTce9/YK+5vOooQHQDL6c5uhPR3JQHAGGOh3sHbA6CRc7RePH7Ujtys1I4wu81eMCpPSIiNDNx2z6Pd5UeOtwiC0AlAHjhwZzuQ/6q+Hzn1Zh2AZAAFAFKNRkN4IBAcBWAI51zfmzpIvT9Kb/AIAHAB2A/gCwAbALT1Rd3Tve/PVm7ANVdM6b+9YEV9xU3zsPL9xSc0+ttEyzlPfv/T1WE79x5wbti6J2Jo9pDRwZAcHggGE7q83Rlt7Z2JgkB1F5oIOOcMAOMclHNOOOcsKjI82O5ytxOCYwCO9g5yCYAD+9YvdX2XaHU+effDL8ncG2ZxznnSsIt/dIsoCjcCGALAdg6HkwEcB7ATwKv71i/d2Pcfc+YvxO71GzFjyjjyk5tmo93ViWuumMIvqEjd2NyK6tomCEJPsCsYlYcbf/6g6YbZ0/03XHNZf2NLDlZgzaYi8uSzb2DFkmdzS8oq8krKKvI3btuTRakwhBAk9E4cxAFzA/I9P/P0nS18APYBWEIIWemwWduyM5JDLyx8iBHyz3979Y0tiI+N6v/9nQ9X0NtuuJItXPzWjqWffJXCOY8YMA7flQYqCPfkjS34wucPssJFC04Q8LrNuzBtcgEuNFE7qmubmCDQbkIIGzMy94R8qrS8Ivy/Hn4m02DQXymJ4rWuTneq2+PV97STUEp/UGZNQBTFmuSEmPoxI3MOPXjvT98ihBS9++GXmHvDrPP+4ocqjiM7I7XvLJPywWdrZvzPS0ti01MT7yqvqIoOBkMQRQGCKIKKIlRZBlPVbz0uYwyM90xKwhw2hIfZUVlVD0oJGOdIT0tumzx14o+2l1TsV1TVVbhoAZ8zfyEKFy24sHPqimM1uicXv4nbrr8isvjAkZlrNuyY3NDUmkhA0ghBdG8U1uzGfiFwFcDRa2dNWfn4A489uLlopTh57Cjf+Xq91RuLrCu+3oq5110+9+uNO28uXLEuPBAIJQsCtZxgnQkCzA47jEYTAj4fujo7T+t+UEpg0OuhqiqGpCbBbjMjFJLx4xuvwj0PPQ2BfjNNEXU6XHPVpfKuY/VXUUL2UULaChctYGfT/n+qcHbuPTDuiefeuJhwXN7p8YqeLq/KOR9KCIk821MrYwyc98+2ZYB3gZBuURAMjDFncmIsdDoJnHPYrBZEO8PA2T9IxwiBp8uLlvYOEEJACMHhimq/IFCEZFkAh45Q0pPjEAJBEP4F4mYhURTVjLREj9FoePe1RY/8gRDie+mtj/HLH1935ilFUyviYyIH5vsxhSvWX/PVhh3O3fvKEnOz0n7W2tYhNre2BznnEqWUnjI+nINKEsKcTuTkpGPWJQV48A+LQAmBoqgQBApCCGRFwcyp46HTSXB7vLA7bDhSUYUOtwcNTa0w6PU4+YMiGgwYO2a4J0DEO9s7u7YwxhoB8DON1oMu6vc+WY1brp0BAHhr2Qrr0s/WGPKHZ1++dvOuK/yB4GRKSRwhRBiQR56uDX1ORAgAFwVBEURBoYSolFLW5fVV5WSkVEVHhtePGZ7T5rBbW8aMymmIjghvIYSUDPZ78vq6b2vrdNt37S2zt7R3WMqPVMZu2VUabtDpTJQSg8qYjTFuU5lqAIfU67qc4qAMssAhiSJunXP5Pp1Bf83dt8+pOa1Lsb8MBSNy++22bbtLY5YUriK3XHv5/cUHDk/atqtkxMHDxw0gYJRQQulZRBdCoNPrIUgSpk/Mx+dfrockCZg2KR+HKmrQ5uqEzx9AbnYaAv4QGFNx3y9vwbwHFkKSxIHOEhjj/S6p3qAH1ekxaXx+W02b+zavz79h+eKHA2eahgyaqD9fvQVXz5gEAHjmpffmvf/p6iS71Tyt0+N1AnASQkz/YIBkAPWco16nE10J8TGV8VERVVHOsMb9ZUePOGxmz7RJBUpSQgwbkZvOLSZT3ZlObAZ7onSSo2HodHuNy9duFYv2lkgbthULP7r6sjxXpyfCHwiOaHd3ZdTUNqYGgsFYAGGEEEmgPRFssFBVhoS4KERFhm9+7ZmHLwaA2oYWJMZ90+bDx6qXLl+9xb5i/TaTw2oZ4+nymV2dHnAOEErwbToemFIQQtDzxJ5bKooQJAmzL5uIouJyqKEgwh1WAAQXjcyF1WYFlSQ0NbeirrkdV02fiOaWVny+eitcnZ2486bZ+GpjESSRYsyIHOSkpyIoh7BtTxk27Cxhw7JTS0YNz7vyx1dPaTjv6cfAU9imHcXJd//uGf11V0574cu1W/NVlZkFgUonxOGefmEcPEhAQiajQTHodUFZVsqzslK/uHRC/qY5V1zSRgip/b7mvoeOViM7Pfl0orikqPhg0uad+2NXrtvhoJSMlGUlq9sfiOOAnpDvHlwUReXOcDu5+8fXLXvutQ+f+NVPr3v64OHjGZuK9mU0t7RDFAVIonjWI84Yh16nQ1RMNLxuN9xdXbBZrRAoQaenC2arFXJIxqzpE5ASH41whxUP/ukFSJKAQEjGnCun4/Ip4xAf5cSSwpVweXxQVBVXTJ8InSQiwm4BOIckidi1rwxjhmfDaDBAlAR0dvlw94MLkZmaMPu1vzy0/J+SU1fVNr7yq98vSgqFQqPcXb4wzrl4chRijHVwziv1en1DTnry0ZF5mVVbd5d8lZOe4r100kXq+PxcDyGk+3Sny38HDh2rQfaQpBMeC8rM8rfXl5m27ymNSkqMvWPT9r0zCSFZlNLvVLbAOYdeJ0FRGRRFYSCEEgKc62cmFJIxd85MGMxmZKYlYc36HVi9eTueWHAXdu4vx6q1WzH/7tuxfM1W5GakYGLBMAgCxabte1H45TrMnDIOo4ZnwWa1oai4FHv2lWPimBFYtvxrxEZHISczDbMvmwgKAq/fD0IAk7HHI4h0WCEIAo7XNGDxGx+0ffbqU5Gc8zM6y53Ru91Tehj5w7IAAMVlxyJfeqcwnzP2zva9B50mgx6k12rjvOcfvV7nd9gsjb7uwNrxo3JX/ObuueUOq/mI5mP8XTFKP7n/yfmd7q55TS3tcYQMRuz+7oRkBT+7aTbCnWEId9hQV9+Ml975BIqsQKQUok6ExWyGKArISE3G6JG50IkCOFOhhEJYsXYrVE7x89uugbuzCyVlR3DnLbPxh7+8ik5vNzJSE3GkthHD0lNx6cR8fLFmE6ZOyke0Mxx2ixk+vx8cFGs2bq+7atr4PwzLSnt9UCL18rXbcdX08eCc583/779dvaf08JWKoo7knJsJIeCc960I7R0/ZujusSNy2p9c/M6nj/76p2zOzIt9hBD15A+Gxul5ackX1uS4yHkvvPvJ+HaX52Kc2wrdoCHLCm6dMwNx8XFoanNBJ4p4+8MvIVICVVXBGQN6NACFcSTExeDOm2dD0vUI+6E/v4SCkXkIC7MjzGHDyOwhSIx1goDA5/dDr9Ph3seex63XXY5YZwQsRglHq+uRm5EGSaTo6g5AL+nYlqLitt/+54+iz7Td37oSVLSvbOxv/vTCryff8KtxKmOJBKCcQLFbLWU6nbTaaNAvf/e5P+yTBNK+/dNTI3sfmqC/nYLhmV35w7Ke5JzbLr5x3seMsUsH7eC9NmWPLdlzn3MOpqp/t7KOESArIw1vF36F1OR4jBuRA8YZnM5IxEWFY39ZBQAOZ3gYHr3vDvz2yRfw/JsfYkR2OkSdiLysIbDaLSjIy4ROL8EXCOC51z7GuNG5iHBY4Q0EkZeVCgogGAohEAwia0gyQrIMxgSIAkVLm8tf3dTy0dm81VNE/cZHK/HT66/Ayo27xi1+48PHNxbtH805twAkKIlSSf6wzF0zLxm76ukX3/38ucfuY1lpCWzZ3x7TBDwIdAdCAIAv1m7XE0L1g7WCSggBFUVQSkEFAaTXgeGcQwkGoShKb+54IgJlkBUFNpsFiXFRcIbZYDGZwAQdpk0uQHtnF5raOkBECbXNbXCEOxEXFYbkpHjodCIyUpMgigK6AkHI3d0QCMXkCSMhCiJCDDAY9Jg2MR+Nze1Yvm4NRuSkw2DMRFKUE3q9Dq2uTrz83mee6JioF2fe/QRd9cIjZ7QIc0qv/fXVD64+VtNwT+mhygwOftRhs6yQRKF86oQxx+bddk0TIcQHABuL9uOSsSM0JX4HGlraERcV0ZdXW37x8F8ja5taUxRF/VEwJM8FYD5nq48xhDtsUFUVvqCMqMhwpCXGQ2EMnZ0eREY40NLegYamVvh83aDg35hVpKeMhjEVo4bnwmG3otPtxWUTR6P0yHFsKNqPYDAIMBUEPQtRDocNHW4vRg3NhMNhQbjNCllW4PF1Izc9GYxxiAJFY4sLFrMRep0IgMDvD8BkMkIOyQABEqLDIVEKSadjz71RWBsTHbFKpeJTNY2tNWe6skgAoL65HVV1jSNeWrriler6JgMlZNPUCaO/vOvmq/ZGRTiaAKCiqh4ZKfGaEgeJ+X96GYt+9wv4g6GUh595ddreAxVTdTrdRUPTk2KLyytNABe+Q2hGTloiAirD2GHZCCoqunx++IMyFFWB1WKCzWyEzWRCUJFRXdOIbXtKQCkFKIVAKRjn4IzBZrdheG46LAYDwmxm7D1wGDUNrQgpCpiqIjk+GtX1zcjLSEZybCQknYTI8DAsW7kRPn8Q0WE2RITZMDwrDS63Bz5/EF3dAcRFhmN0bjpESUQgEMT+8ips33cAHR1ucEDR6XQNQ3My3i6rql9q1OuOA/Cf8Yriy0uXhwdC8pN7Sw8HGMfBlLiojX+c/9NqQkjw5GiiMbg8uPC1qcXlFX8MKeqo3LRkc0p8TK+lxdHtD6L0yDHUNrWcmYMCwGGzIjE6EjVNzbhsQgHsVjOCsoLuYAhefwD+YAiSKEISBBh0EhTG4A8G4XRY8fGKdSBUABEoIsPDMGZoJlZt3IHkxHhkDUmCUSdiaEYyuv1B7Co9jE27DyAxLhrDstJACNDa2o7IMDtG5WWgrdOD6sZWVFTVIyrCgahwO4LBICRBhM1uARiH1WJE+bEa2MwmqKqK+hYX9hyoYKIohHKHJDULkvRoeVXDFrNB38w49xUuWoAzXVEUiw9Vyi8+Nu+ePpeioqr+BC9QE/TgsfCVD7HgzhuwefcBy3ufr31s94HDc+NiIqOHZw6BQEhPpRpjoITAZjYhIyURDS3t3x6ZenPkhNgojMzNQGVdE8LsFpgMegQ9PsiyAsZYjw0nUAAc/lAIQVmFQAGRCgiPCIPL5YEIApe7C/5AEFFREWjr8CDG40NRZTVS46NgMBiQkhiDLXvL0NjqQkpCDOwWE3LSU1Db1Iqapja4fd1odXlgtZjhC4TQ5Q9CEgSUVdbBZtYjwmFHZ5cXFpMZOr0eJYcqA8drGpqGZqV2x8dEHl2/6+ALFpOhxKjXtX70198qc+YvBACcde3H5j0HMTk/T1Peeeb9FRuHrthQtNTvDw7NSkuEw2rt2W9GKSglPZM5QiAKAggBPv56yz/c98cYQ0ZKPAx6A2w2K/SSCLPRALPJAEVR4O0OQFYZBPqN+8E5h0AFSCKF0aDHyg1FCPgDCCkKoiIjEBMVjrJjtaAAdDoJU8eNRFVdI+KcYUhOiEGMMwx1ja14/ePV0Osl2MwmMMZgNRuhk0RkpCSis8sLs9kEWZbBOdDZ5YXP142mtk5YTQZ4fH7ER0WgorbxxbzM1JbKhtbVqqKGQrLitZj07ZyjvXDRAna2ZadnvPiiMTh8sW5HxNIvNuwWRZqSlZbcU+1HKARKTitqgVIUHTyEqvrmv1ufYbeacf1lk1Db0g5fUEZIVnryYc7BwRGSVeglEXpJhKIy2CwmxEeFwW624JO1WxBmteJAxfEezxkApRQFo/LQ6nKjprEVlBKMzE5DuN2KI5V16A4EYDMbMWvqReCM442PVyMQCiEUCPZPNFXG+t2VvlWkvrMJFShMBn1w5sUFvoXvLh87LC2BoGdrVzd6itjUvs0B5yLoM/KpNQYHznnK7Q/+tZBKYkpGcjw44yACGeg59N/w3ghMKYXVaAQRhL8raqvFBEoJwu0WCN4APL5uGA16qIwhJCvgLICQrEBWVEiiAEkUwBSGDTv3oaWjC1mpiYjzONHYm+YQSsGYCr1OB1GkUFWGitpGjHNY0dLpRjAkIyjLaHd50OH14dJJowFOcODIcYTZzdhRXA5Jkk5pp8IYj4uOICGFPTI6L333Cx+t2T0yIymgqizQK+RTnnMuggbOY2mkRg9N7Z14ZuFTqJXtc1s7PD9OjImkBr0OtG8hhPRUyVFCwHlPpOyr55YEAY0uF1we3wmPD/yhhMJqNqKkogb+QBBmowGHq+oxJmcIwu1WMMahqAw6UYTDZobRoMeR6ka0uz2YNbkAbq8fJUeO99c/A0BkRBj0egkOqxmcA253F1QG5OcNQVNbB7q7AyguP4bDVfWIctih14lIiotEXX0b2txdp23riJz0zlW7ylLtFtPehlbX4fWvPN5Vtm21nDP+Mn6u4tXSj39xlP6PeX9azjjPs5sNyElNAmccVOhNNXptNJCe3FoSBfj8IVTUNaChrePbjg3OORxWC66dMgbbDxzDkep6hDvsuGrSaMiyijaPGwIRYDUbICsMoASSKMDt7cbaHfuhMnbC4ovJoMeYYZnYW16J9MQYOB1WrNxajDCrCZQQeLzdp7x+3yLP3ys4GjM0o23L/iO3Wk2GHYWLFni+S3qhifpCyKU37Lr+5Q9WvU4FauWMw2DQITshFga9DqIggAocFAJEShGQQzja0IL6FpffZNCV6nS63aGQfGNIUZzfJm5ZViCKvakKIeAARmelINYZAbvZAFEU4AvIYKqMDk83jje1oL7Z1Z+DDzgYLGYjhmWkoL6lHeDA6Nw0fL5hZ28x/9kjCQSx0VEL6lvaPyCEVJ8PMWui/udGat1tDz+3y+sPpKFnlZAYJBHxkWEw6Q3oKw9t6nSjrcMDWWUwG3SlD995w0+GZSTtfW7JirvWbN/3tCgKlrMdM845dJKIWKcDF+Wmg6kM3SEZBBRBOYgdByrg8wf7N8MOrH4lhCAxJgJ6SYJep4PNbMDGPQd76rLPEsYYT0+KWV1Z1/IIpbQEQOh8CVsT9SBSWdeMtITTF5M9+sLSxNKK2pcATEfPVaJOiZCUEKiMITctcffT980tAIBn312O++ZehZc+/Op363cdnBSSlUQAWWc7yeecQ2UMkQ4LEqMjYLOYEWazQCQULZ0eiCLtWVgpqzzleZIoICQruGLiKNQ3t+FAZf2JfwMOcCDMZkYwpCAQCp1SSkIIEGG31nPwu1xu7xYAHZqoL2Ca2zsRHeEAALjc3jx/MMgICKeUyKrKxDC7JZ4x5vlsw647P1i97VaB0tPWdIiiELz3plkvTxqd818DH3/+vRW495YrsWnPQevHX+8YWdPU9hAh5FL0XPXo3Aa+d3IKAkTZLUiMiYIgEGwvrej/G50oIKSo/eLOSYvHhOHZ+OCrLejyB0EI8TDGGhKiIywpcVHr9pZXvpWRFPtA8aHjM0TxVA/CZNCDcXZLIChvBVDzXRwOTdTnma937B+9p7zyj6UVNUld3X5KTrToBMZ4kABNHDxdFISUga4TB6AqKrJT4/1zpo+7ctzwzPWVdc0kLSH6hFhXWlGNYRk9W8WWfbU1dnvJ4bsaWly3hWQlaTB2zDDWYy6KQk/dR0pMBKxmE0qP1fY7MyFZxl03XhZ02u3Nq7YXHzle3/p53pDEPau2Fh9td3uVIQnRSuGiBd6/LVv5+rqi0qkATtjywzjH0PTE93cdOPa02agvLVy0QNUi9QVISFaMDz2/5KvKuqZJvTP/vmvzDdQtR89VpASceA0/xWIytMy+pODA8IykX2alxDe9v2oLbpo56Vtfd095JfJz0vDW5+v/e/mmPXkqY1kAEtCzk108g/RE7R3/Uz4QisowYUQmbCYjvtqxHzpJhFEvYeKI7O6pF+W9snnv4Teb2zvad5dVugAEe31m3rucTdBz7cKPAMw8WdT52als1fb9edHh9qOFixYo52NMtMWX78jusmNyhN3yVFrC8DfKK+s9VpNhmz8YcnGAg3O/JIlBgZKKzOR4e3SEnVJKXZIodIzITOl2OqwuSunBt5/45nhnImgAyM9Jwxcbd2H2JQW/55ybt+4rj1m9fb+zvqUjPibCPoIQMlUUhfGKooout/fE8MXBVcZ2dXh8RFbVPNJz4ct+Zk0YiaN1TbCbjQCAvNTEbmeYtSraGbbyhWVfP/7sgp90ndyeAfYcv+a+pwxZybHikeomnFwT3h0I0q1vfnZszvzb2fkaEy1SDwJnGl0vNBRFzfjx7xcv9wdDmf1RTqCYftFQxDsjUFZVq+4oPdqSNyTxs8ToiBf/+MpHh/5zzqWhR39x4z887n/c93TaqOyU5/YeOn7VwKsvcc6REheJuhZXJmO8izHWFQjJQavZqHyw8P5B8621FcVB4KN3X/9etptFZTubXe5bey/yiMhwG1RFRcnRWlTWt/BZE0cXUYJHNhcfevXZBXdUe47tUdcv/xBz5i9E+fY1p0Tq8u1rMGf+QgogJ9xhvbjV5R5CBqzGEELg8niRGBMx1+Pz88SYiCGXTxh54xP33LJmzvyFZLAmjVqk/gFz7a+fjiKErAYwAgASIsMRHx0OT5cPk0Zl11XUtsxfuW3fWqNe6jyTirk58xfqZEWNirBbCjKTYn9bdODo+L4r3J48NxUo9TLOVFlRzfGR4e80tHX8VqDUNRjCptrQ/nCxW819E9aedISpaO/sgt1mRn1b5+drivZvMuol9xkKmgAwTh6dOxLAAzsPHr2op1LwtG4LyUiKtSoK+9+xwzIkXyB4B+c8EoDQVzutiVrjnJAEIQZAbN/vsqIi1hmGmHBHx9ptJW8Rg9RauGiBeia5buGiBZxzHkyLd3rHDE0PTSsYWjOlILfWbjYqfQtMAqVcEoUgIaTzYGWtYrcar/l6R+ktwzKSC/2BkARAGIxIrbkfP2CcDuuYdndX/+VPWzs8aLG74fUHypc+c//Ok1yNb4+QhAR+9vjLm+KcjhnJcZFxkihmWkyGsRnJsY9VVDcyh9UcJIQ8Qimhze2dN3h8gYtunDHhzy9/tHrKkMQYF+dcHozJoibqHzARDmsUqr+ZV1FKUV7dAAIStvdQZeLo7LTasxEYB+De8jabPn9hEEAtgFBIVsTq+tZ7JVG8NxAKSZIgrCs7Xnf8ktG57uYOT2Rdc1vqvg8K6/bh+KB51lr68QOmtKJmJ3oWggZGWxCCIU+9Vjj9bI83YHMsL1y0oPdKtnyzwtj65Fjn/wLoAoGcFBPpKTtetyTCbp3BOM8FWgZ1EUZzP37A3P2n/8tqdrm3cc7DeyZwgNWkB6UUNotpWVZy3B333HRF93d5jTnzF4ISItW3uiLn3Tzr+sNV9Z+UVtTUnfx9LoOJFql/wFx36TivQKmn73fGGTKSY5GTmoCMxJhLlm/em90nzHMVdOGiBWCcy7HOsJb3vtz8f/sPVzcOFPRguB1apNb4Jgfm3HDTA/+zTFaUq/vEkJ+TCn9Qhs8fVHyBwOMv//6uJwb7dc/XjhctUmuAEBKYMiZvM+vdzqIwBkXl8AeCsFtNYmJ0ZMHNDyxyDPbrnk9Ba6LWwC9vmPGRKAq1vSJHW4cbjPd87UYgGErs8HptV9/79PfqjK6JWovWVaNz0goBKJQQ1LV29HwjgSRh3NCM1JnjRzs/f/4Brola43vDup2lGJmV8jLn6N+j1enthqurC+99tdmx6+DRWzjnUt+E7nxM7DRRawwq0y4ahlmT8g/dfMWk33DOtwOQ3d5uVNa1IhBSoDJ26+rt+7MLFy3AVfOeFACQC13gmqg18Nona3HjjAkfRditsy8dO/xFxrmrr2A0JCvRn64rWvz5+l2zM5JiE1dt2+doaO3Q9U34LkRha5aeRj9933710PPvrjxc1dC/FYsDnKmsKz0phqfFR7tLK6ofMRp0R4oPVR2cOXGU98E7rj3vNp0mao1zZs78hcarpxT87tN1RfdbTUaDwtjbVpPh9uZ2N6eUEA4wSggz6qWO3LTE2t/deX2+ln5oXOjIP7l66qOU0uqEaGeZx9u9raqx9WcjMpMPCZS2UkK4USeKwZBi2VFaMfr+v77Jn3nrs6maqDUuZBQAzGzUq8lxzkf0OmmFxWjYcrCy7o7Jo7LXyooa5GCQVXVxQd4QHKluZMWHji9eta14qJZTa1yw3PrQs2TJn+87wZu+7v6/WIsOHA2/4+pLdpdU1DpHZafevnZnafMl+blPlh6t0ZmN+vuXPHnfGi1Sa1yQLPnzffxk245z3j0mJ1WsrG95C+D+5OiIuHCbeV9RacUv5866WM5LS/zoQmm/th9vMG8AAAB2SURBVElA47T0ORkDbDuVUqqajXqJEGKw2y3dB4/Vto7JHeK7/rJZE4COYGVdI9ISYrX0Q+N75YzYCCEjAOiMel2p29vdIg24Zt6FYulpkVrjbOjinO8EQLoDwdAXzz+k9YiGhoaGhoaGhoaGhoaGhobGP53/B2R/emxDj39jAAAAAElFTkSuQmCC
      mediatype: image/png
  labels:
    alm-owner-teiid: teiid-operator
    operated-by: teiid.0.0.1
  selector:
    matchLabels:
      alm-owner-teiid: teiid-operator
      operated-by: teiid.0.0.1
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  customresourcedefinitions:
    owned:
    - version: v1alpha1
      kind: VirtualDatabase
      description: A project prescription running a teiid service.
      displayName: VirtualDatabase
      name: virtualdatabases.core.teiid.io
      resources:
      - kind: DeploymentConfig
        version: apps.openshift.io/v1
      - kind: Secret
        version: v1
      - kind: PersistentVolumeClaim
        version: v1
      - kind: Service
        version: v1
      - kind: Route
        version: route.openshift.io/v1
      - kind: BuildConfig
        version: build.openshift.io/v1
      - kind: Build
        version: build.openshift.io/v1
      - kind: ImageStream
        version: image.openshift.io/v1
      specDescriptors:
      - description: Runtime
        displayName: Runtime
        path: runtime
        x-descriptors:
        - "urn:alm:descriptor:com.tectonic.ui:label"
      statusDescriptors:
      - description: Deployments for the VirtualDatabase environment.
        displayName: Deployments
        path: deployments
        x-descriptors:
        - "urn:alm:descriptor:com.tectonic.ui:podStatuses"
      - description: The address for accessing teiid service, if it is deployed.
        displayName: Route
        path: route
        x-descriptors:
        - "urn:alm:descriptor:org.w3:link"
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: teiid-operator
        rules:
        - apiGroups:
          - ""
          - core.teiid.io
          - apps.openshift.io
          - image.openshift.io
          - build.openshift.io
          - route.openshift.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - teiid-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
      deployments:
      - name: teiid-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: teiid-operator
          template:
            metadata:
              labels:
                name: teiid-operator
            spec:
              serviceAccountName: teiid-operator
              containers:
              - name: teiid-operator
                image: quay.io/teiid/teiid-operator:0.0.1
                command:
                - teiid-operator
                imagePullPolicy: Always
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace              
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['name']
