apiVersion: apps/v1
kind: Deployment
metadata:
  name: teiid-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: teiid-operator
  template:
    metadata:
      labels:
        name: teiid-operator
    spec:
      serviceAccountName: teiid-operator
      containers:
        - name: teiid-operator
          # Replace this with the built image name
          image: quay.io/rareddy/teiid-operator:v0.0.1
          command:
          - teiid-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "teiid-operator"
